/*
**
** File: cf_external_functions.h
** This file is automatically generated by the
** chain flow assembler
** Build Time: 2017-08-11 12:30:31.639539  
**
*/

#ifndef _EXTERNAL_FUNCTIONS_H_
#define _EXTERNAL_FUNCTIONS_H_ 

#include <project.h>
#include "cf_chain_flow_support.h" 
#include "cf_events.h"
/*
This is the symbolic definitions of the chains
*/



#define  initialization   0
#define  second_tick_chain   1
#define  minute_tick_chain   2
#define  hour_tick_chain   3
#define  measure_channel   4
#define  one_wire_presence   5
#define  make_soil_measurement   6
#define  make_air_temperature   7
#define  flash_update   8
#define  heart_beat   9
#define  commissioning_heart_beat   10
#define  handle_commissioning   11



/*
This is the symbolic definitions of the links for chain initialization
*/
#define  initialization_0   0
#define  initialization_1   1
#define  initialization_2   2
#define  initialization_3   3
#define  initialization_4   4
#define  initialization_5   5
#define  initialization_6   6
#define  initialization_7   7
#define  initialization_8   8
#define  initialization_9   9
#define  initialization_10   10
#define  initialization_11   11
#define  initialization_12   12
#define  initialization_13   13
#define  initialization_14   14
#define  initialization_15   15



/*
This is the symbolic definitions of the links for chain second_tick_chain
*/
#define  second_tick_chain_0   0
#define  second_tick_chain_1   1
#define  second_tick_chain_2   2
#define  second_tick_chain_3   3
#define  second_tick_chain_4   4



/*
This is the symbolic definitions of the links for chain minute_tick_chain
*/
#define  minute_tick_chain_0   0
#define  minute_tick_chain_1   1
#define  minute_tick_chain_2   2
#define  minute_tick_chain_3   3



/*
This is the symbolic definitions of the links for chain hour_tick_chain
*/
#define  hour_tick_chain_0   0
#define  hour_tick_chain_1   1
#define  hour_tick_chain_2   2
#define  hour_tick_chain_3   3
#define  hour_tick_chain_4   4
#define  hour_tick_chain_5   5
#define  hour_tick_chain_6   6
#define  hour_tick_chain_7   7



/*
This is the symbolic definitions of the links for chain measure_channel
*/
#define  measure_channel_0   0
#define  measure_channel_1   1
#define  measure_channel_2   2
#define  measure_channel_3   3
#define  measure_channel_4   4
#define  measure_channel_5   5
#define  measure_channel_6   6
#define  measure_channel_7   7
#define  measure_channel_8   8
#define  measure_channel_9   9
#define  measure_channel_10   10



/*
This is the symbolic definitions of the links for chain one_wire_presence
*/
#define  one_wire_presence_0   0
#define  one_wire_presence_1   1
#define  one_wire_presence_2   2



/*
This is the symbolic definitions of the links for chain make_soil_measurement
*/
#define  make_soil_measurement_0   0
#define  make_soil_measurement_1   1
#define  make_soil_measurement_2   2
#define  make_soil_measurement_3   3
#define  make_soil_measurement_4   4
#define  make_soil_measurement_5   5
#define  make_soil_measurement_6   6
#define  make_soil_measurement_7   7



/*
This is the symbolic definitions of the links for chain make_air_temperature
*/
#define  make_air_temperature_0   0
#define  make_air_temperature_1   1
#define  make_air_temperature_2   2



/*
This is the symbolic definitions of the links for chain flash_update
*/
#define  flash_update_0   0
#define  flash_update_1   1
#define  flash_update_2   2
#define  flash_update_3   3



/*
This is the symbolic definitions of the links for chain heart_beat
*/
#define  heart_beat_0   0
#define  heart_beat_1   1
#define  heart_beat_2   2
#define  heart_beat_3   3



/*
This is the symbolic definitions of the links for chain commissioning_heart_beat
*/
#define  commissioning_heart_beat_0   0
#define  commissioning_heart_beat_1   1
#define  commissioning_heart_beat_2   2
#define  commissioning_heart_beat_3   3



/*
This is the symbolic definitions of the links for chain handle_commissioning
*/
#define  handle_commissioning_0   0
#define  handle_commissioning_1   1
#define  handle_commissioning_2   2
#define  handle_commissioning_3   3
#define  handle_commissioning_4   4
#define  handle_commissioning_5   5
#define  handle_commissioning_6   6
#define  handle_commissioning_7   7
#define  handle_commissioning_8   8
#define  handle_commissioning_9   9
#define  handle_commissioning_10   10
#define  handle_commissioning_11   11



int set_new_moisture_measurement_flag(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int update_modbus_rtc_values(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int set_commissiong_address(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int set_source_channel(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int  toggle_heart_beat(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int find_one_wire_devices(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int set_modbus_watch_dog_flag(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int set_sink_channel(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int start_ds18B20_temperature_measurement(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int remove_power(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int pat_watch_dog(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int program_flash(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int set_modbus_reset_flag(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int switch_on_fn(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int measure_air_temperature(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int enable_interrupts(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int update_new_measurement_available(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int restore_system_parameters(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int switch_off_fn(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int set_normal_modbus_address(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int clear_new_moisture_measurement_flag(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int make_source_measurement(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int initialize_analog(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int init_moisture_processing(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int make_dummy_measurement(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int read_ds18B20_temperature_measurement(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int initialize_modbus_bus(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);


int set_minute_rollover_flag(unsigned link_id, unsigned param_1,
  unsigned param_2, unsigned param_3, unsigned event, unsigned data);






#endif
